id: A400F4E36
title: Aspiration for the Long Life of Dezhung Rinpoche (Jampa Kunga Tenpé Nyima)
type: translation
pechas:
- I19D7C5BB
- I15D2B646
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:34:54.467475
  last_modified_at: 2023-01-04 11:34:54.467487
  collections:
  - Dezhung Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I19D7C5BB/874D: 98B5
  I15D2B646/8180: 98B5
